services:
  proxy:
    image: nginx
    restart: always
    volumes:
      - /run/letsencrypt:/run/letsencrypt
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf # Change this later will have nginx conf stored in the github
  db:
    image: postgres:latest
    restart: always
    secrets:
      - db_root_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
      POSTGRES_USER: administrator
      POSTGRES_DB: utsa_marketplace
  backend:
    ports:
      - "5000:5000"
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
  frontend:
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    build:
      context: frontend
secrets:
  db_root_password:
    file: db_password.txt
