services:
  db:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
        POSTGRES_USER: administrator
        POSTGRES_DB: utsa_marketplace
  backend:
    depends_on:
      - db
    links:
      - db:database
    build:
      context: backend
    restart: always
  frontend:
    build:
      context: frontend
secrets:
  db_root_password:
    file: db_password.txt
